name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: "World"
        type: string

permissions:
  actions: read
  contents: read

jobs:
  say-hello:
    name: Say Hello
    runs-on: windows-latest

    steps:
      # Change @main to a specific commit SHA or version tag, e.g.:
      # actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
      # actions/hello-world-javascript-action@v1.2.3
      - name: Print to Log
        id: print-to-log
        uses: waiwaing/js-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
